include(InstallRequiredSystemLibraries)

set(CPACK_PACKAGE_CONTACT "denismalyi2204@gmail.com")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "denismalyi2204@gmail.com")

set(CPACK_PACKAGE_VERSION_MAJOR 1)
set(CPACK_PACKAGE_VERSION_MINOR 0)
set(CPACK_PACKAGE_VERSION_PATCH 0)
set(CPACK_PACKAGE_VERSION_TWEAK 0)
set(CPACK_PACKAGE_VERSION "1.0.0.0")

set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Quadratic equation solver")
set(CPACK_PACKAGE_DESCRIPTION_FILE ${CMAKE_CURRENT_SOURCE_DIR}/DESCRIPTION)
set(CPACK_PACKAGE_NAME "solver")
set(CPACK_PACKAGE_FILE_NAME "solver-${CPACK_PACKAGE_VERSION}-${CMAKE_SYSTEM_NAME}")

set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_CURRENT_SOURCE_DIR}/LICENSE)
set(CPACK_RESOURCE_FILE_README ${CMAKE_CURRENT_SOURCE_DIR}/README.md)

# Linux RPM
set(CPACK_RPM_PACKAGE_NAME "solver")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_GROUP "Development/Tools")
set(CPACK_RPM_CHANGELOG_FILE ${CMAKE_CURRENT_SOURCE_DIR}/ChangeLog.md)
set(CPACK_RPM_PACKAGE_RELEASE 1)

# Linux DEB
set(CPACK_DEBIAN_PACKAGE_NAME "solver")
set(CPACK_DEBIAN_PACKAGE_RELEASE 1)

# Windows WIX
set(CPACK_WIX_UPGRADE_GUID "12345678-1234-1234-1234-123456789012")
set(CPACK_WIX_PACKAGE_NAME "Solver")

# macOS DragNDrop
set(CPACK_DMG_VOLUME_NAME "Solver Installer")
set(CPACK_DMG_FORMAT "UDRO")

# Components
set(CPACK_COMPONENTS_ALL solver)

include(CPack)

# Windows WIX specific settings (required)
set(CPACK_WIX_UPGRADE_GUID "12345678-1234-1234-1234-123456789012")
set(CPACK_WIX_PRODUCT_GUID "87654321-4321-4321-4321-210987654321")
set(CPACK_WIX_PACKAGE_NAME "Solver")
set(CPACK_WIX_INSTALL_SCOPE "perMachine")

# Create a minimal license file for WIX
file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/license.rtf "This software is licensed under MIT License")
set(CPACK_WIX_LICENSE_RTF ${CMAKE_CURRENT_BINARY_DIR}/license.rtf)
